version: '3.9'

services:
  postgres:
    container_name: libra_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=libra_admin
      - POSTGRES_PASSWORD=libra_pwd
      - POSTGRES_DB=libra_view