server:
  port: 8081

spring:
  application:
    name: libra-view-tmdb
  r2dbc:
    url: r2dbc:postgresql://localhost:42001/libra_view_tmdb
    username: libra
    password: Admin123
  sql:
    init:
      platform: postgres

app:
  tmdb:
    authentication:
      token: # TMDB access token
  client:
    http:
      address: