CREATE TABLE genre
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id BIGINT,
    name    VARCHAR(255),
    CONSTRAINT uc_genre_tmdb_id UNIQUE (tmdb_id)
);

CREATE TABLE cinematic
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discriminator VARCHAR(255) NOT NULL,
    tmdb_id       BIGINT,
    title         VARCHAR(255),
    release_date  TIMESTAMP WITHOUT TIME ZONE,
    overview      VARCHAR(5000),
    poster_path   VARCHAR(255),
    backdrop_path VARCHAR(255),
    vote_average  DOUBLE PRECISION,
    vote_count    INTEGER,
    popularity    DOUBLE PRECISION
);

CREATE TABLE cinematic_genre
(
    cinematic_id BIGINT NOT NULL,
    genre_id     BIGINT NOT NULL,
    CONSTRAINT pk_cinematic_genre PRIMARY KEY (cinematic_id, genre_id)
);