openapi: 3.0.3
info:
  title: LibraViewCineRegistry API
  version: 0.0.1
servers:
  - url: http://localhost:8081/master
paths:
  /user/login:
    post:
      summary: Login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./libra_view_master.components.yaml#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "./libra_view_master.components.yaml#/components/schemas/AuthNResponse"
