openapi: 3.0.3
info:
  title: LibraViewCineRegistry API
  version: 0.0.1
servers:
  - url: http://localhost:8082/cine-registry
paths:
  /genre/page:
    get:
      summary: Genre page
      operationId: getGenrePage
      responses:
        "200":
          description: OK
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/GenreDTO"
  /cinematic/page:
    post:
      summary: Return general data for the specified paged request
      operationId: getCinematicPage
      parameters:
        - name: userLibrary
          in: query
          required: false
          schema:
            type: boolean
        - in: query
          name: type
          required: true
          schema:
            $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/CinematicType"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./common.components.yaml#/components/schemas/PageableRequest"
      responses:
        "200":
          description: OK
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/GeneralCinematicDTO"
  /cinematic/{referenceId}:
    get:
      summary: get Cinematic
      operationId: getCinematic
      parameters:
        - in: path
          name: referenceId
          required: true
          schema:
            $ref: "./common.components.yaml#/components/schemas/IdData"
        - in: query
          name: type
          required: true
          schema:
            $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/CinematicType"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                  $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/CinematicDTO"
        "204":
          description: No Content
    post:
      summary: Store cinematic
      operationId: storeCinematic
      parameters:
        - in: path
          name: referenceId
          required: true
          schema:
            $ref: "./common.components.yaml#/components/schemas/IdData"
        - in: query
          name: type
          required: true
          schema:
            $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/CinematicType"
      responses:
        "201":
          description: Created
  /user/cinematic:
    get:
      summary: Check cinematic(s) in user library
      operationId: checkCinematicInUserLibrary
      parameters:
        - in: query
          name: referenceIds
          required: true
          schema:
            $ref: "./common.components.yaml#/components/schemas/IdArrayData"
        - in: query
          name: type
          required: true
          schema:
            $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/CinematicType"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.components.yaml#/components/schemas/IdArrayData"
        "204":
          description: No Content
    post:
      summary: Add cinematic(s) to user library
      operationId: addCinematicToUserLibrary
      parameters:
        - in: query
          name: referenceIds
          required: true
          schema:
            $ref: "./common.components.yaml#/components/schemas/IdArrayData"
        - in: query
          name: type
          required: true
          schema:
            $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/CinematicType"
      responses:
        "201":
          description: Created
    delete:
      summary: Delete cinematic(s) to user library
      operationId: deleteCinematicFromUserLibrary
      parameters:
        - in: query
          name: referenceIds
          required: true
          schema:
            $ref: "./common.components.yaml#/components/schemas/IdArrayData"
        - in: query
          name: type
          required: true
          schema:
            $ref: "./libra_view_cine_registry.components.yaml#/components/schemas/CinematicType"
      responses:
        "200":
          description: Ok