server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:42002/libra_view_cine_registry
    username: libra
    password: Admin123
  sql:
    init:
      platform: postgres

logging:
  config: classpath:logback-config.xml
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

app:
  jwt:
    secret-key: # wich will be used by the JWT service
    expiration-time: # in sec
  tmdb:
    authentication:
      token: # TMDB access token
  client:
    http:
      address: