CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    CONSTRAINT uc_user_email UNIQUE (email)
);

CREATE TABLE user_cinematic
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULl,
    reference_id BIGINT NOT NULL,
    added_at     TIMESTAMP,
    comment      VARCHAR(5000),
    CONSTRAINT uc_user_cinematic_user_id_reference_id UNIQUE (user_id, reference_id)
);