openapi: 3.0.3
info:
  title: LibraViewTMDB API
  version: 0.0.1
servers:
  - url: http://localhost:8081
paths:
  /movie/details:
    get:
      summary: Returns detailed data for specified movies
      operationId: getMovieDetails
      parameters:
        - name: tmdbIds
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        "200":
          description: OK
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: "./libra_view_tmdb.components.yaml#/components/schemas/CinematicDTO"