<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.0</version>
        <relativePath/>
    </parent>

    <groupId>hu.bozgab</groupId>
    <artifactId>libra-view-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>LibraView</name>
    <description>Parent POM for LibraView applications</description>

    <modules>
        <module>libra-common</module>
        <module>libra-view-master</module>
        <module>libra-view-cine-registry</module>
    </modules>

    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <properties>
        <java.version>21</java.version>

        <!--  Keeping this version for postgres version 16 (bug)  -->
        <!--  https://github.com/flyway/flyway/issues/3807  -->
        <flyway.version>10.0.1</flyway.version>

        <libra.view.lombok.version>1.18.38</libra.view.lombok.version>
        <mapstruct.version>1.5.5.Final</mapstruct.version>

        <libra.view.spring.test.version>3.5.0</libra.view.spring.test.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- spring -->

            <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-webflux -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-webflux</artifactId>
                <version>3.5.3</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-r2dbc -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-r2dbc</artifactId>
                <version>3.5.3</version>
            </dependency>

            <!--            &lt;!&ndash; https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-jpa &ndash;&gt;-->
            <!--            <dependency>-->
            <!--                <groupId>org.springframework.boot</groupId>-->
            <!--                <artifactId>spring-boot-starter-data-jpa</artifactId>-->
            <!--                <version>3.5.3</version>-->
            <!--            </dependency>-->

            <!-- r2dbc -->


            <!-- postgresql -->

            <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>42.7.7</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.postgresql/r2dbc-postgresql -->
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>r2dbc-postgresql</artifactId>
                <version>1.0.7.RELEASE</version>
            </dependency>

            <!-- flyway -->

            <!--  https://mvnrepository.com/artifact/org.flywaydb/flyway-core  -->
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-core</artifactId>
                <!--  Not necessary but keep it here  -->
                <version>${flyway.version}</version>
            </dependency>
            <!--  https://mvnrepository.com/artifact/org.flywaydb/flyway-database-postgresql  -->
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-database-postgresql</artifactId>
                <version>${flyway.version}</version>
                <scope>runtime</scope>
            </dependency>

            <!-- mapstruct -->

            <!--  https://mvnrepository.com/artifact/org.mapstruct/mapstruct  -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <!--  https://mvnrepository.com/artifact/org.mapstruct/mapstruct-processor  -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
                <scope>provided</scope>
            </dependency>

            <!-- lombok -->

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${libra.view.lombok.version}</version>
                <optional>true</optional>
            </dependency>

            <!-- openapi -->

            <!-- https://mvnrepository.com/artifact/org.openapitools/openapi-generator-maven-plugin -->
            <dependency>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.13.0</version>
                <scope>provided</scope>
            </dependency>

            <!-- javax -->

            <dependency>
                <groupId>javax.annotation</groupId>
                <artifactId>javax.annotation-api</artifactId>
                <version>1.3.2</version>
            </dependency>
            <dependency>
                <groupId>javax.validation</groupId>
                <artifactId>validation-api</artifactId>
                <version>1.1.0.Final</version>
            </dependency>
            <dependency>
                <groupId>javax.servlet</groupId>
                <artifactId>javax.servlet-api</artifactId>
                <version>3.0.1</version>
                <scope>provided</scope>
            </dependency>

            <!-- TEST spring -->

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <version>${libra.view.spring.test.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
