server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:42001/libra_view_master
    username: libra
    password: Admin123
  sql:
    init:
      platform: postgres

app:
  jwt:
    secret-key: # wich will be used by the JWT service
    expiration-time: # in sec
  client:
    http:
      address: