<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>hu.bozgab</groupId>
        <artifactId>libra-view-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>libra-view-tmdb</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>LibraViewTMDB</name>
    <description>LibraViewTMDB application</description>

    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <dependencies>
        <!-- parent defined -->
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator-maven-plugin</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </dependency>
        <!-- TEST -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <!-- self defined -->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>tmdb-api-generator</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>

                            <inputSpec>${project.basedir}/../../LibraViewContract/tmdb/openapi_source.json</inputSpec>
                            <output>${project.build.directory}/generated-sources/tmdb</output>
                            <cleanupOutput>true</cleanupOutput>

                            <apiPackage>hu.bozgab.tmdb.generated.api</apiPackage>
                            <modelPackage>hu.bozgab.tmdb.generated.model</modelPackage>
                            <invokerPackage>hu.bozgab.tmdb.generated.client</invokerPackage>

                            <configOptions>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>

                            <nameMappings>
                                <nameMapping>_id=underScoreId</nameMapping>
                            </nameMappings>

                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                        </configuration>
                    </execution>
                    <execution>
                        <id>libra-view-tmdb-api-generator</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <generatorName>spring</generatorName>
                            <library>spring-boot</library>

                            <inputSpec>
                                ${project.basedir}/../../LibraViewContract/libra-view/libra_view_tmdb.api.yaml
                            </inputSpec>
                            <output>${project.build.directory}/generated-sources/libra-view-tmdb</output>
                            <cleanupOutput>true</cleanupOutput>

                            <apiPackage>hu.bozgab.LibraViewTMDB.generated.api</apiPackage>
                            <modelPackage>hu.bozgab.LibraViewTMDB.generated.model</modelPackage>
                            <invokerPackage>hu.bozgab.LibraViewTMDB.generated.client</invokerPackage>

                            <configOptions>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                                <openApiNullable>false</openApiNullable>
                                <useResponseEntity>false</useResponseEntity>
                                <serializableModel>true</serializableModel>
                                <interfaceOnly>true</interfaceOnly>
                                <reactive>true</reactive>
                                <useSpringBoot3>true</useSpringBoot3>
                            </configOptions>

                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
